version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  localstack:
    image: localstack/localstack:2.2
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  cache:
    driver: local
